apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadzhwe1118-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadzhwe1118-tenant-component
    app.kubernetes.io/part-of: loadzhwe1118-tenant-app
  name: loadzhwe1118-tenant-component
  namespace: loadzhwe1118-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadzhwe1118-tenant-component
    weight: null
status: {}
